modLoader = "javafml"
loaderVersion = "[46,)"
license = "CC BY-NC-ND 4.0"
showAsResourcePack = false
clientSideOnly=true # stop loeading mod on servers

[[mods]]
modId = "crop_marker"
version = "${version}"
displayName = "FullGrownCropMarker"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/full-grown-crop-marker"
#logoFile="examplemod.png"
#credits=""
authors = "Buecher_wurm"
description = '''Adds a little marker over all crops that are at their maximum age!'''
displayTest = "IGNORE_ALL_VERSION" #client only mod

[[dependencies.crop_marker]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crop_marker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
