name: Build and Publish Release

on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  MODID: "crop-marker"
  CURSEFORGE_ID: 834457
  CURSEFORGE_LINK: "https://curseforge.com/minecraft/mc-mods/full-grown-crop-marker"
  MODRINTH_ID: "zB8NzHon"
  MODRINTH_LINK: "https://modrinth.com/mod/full-grown-crop-marker"
  MODRINTH_FEATURED: false # if this version should be featured on modrinth
  DISCORD_COLOR: 15216972
  DISCORD_MENTION: "<@&1133751307086352514>"
  DISCORD_TITLE: "New version for FullGrownCropMarker just released :exclamation:"
  DISCORD_THUMBNAIL: "https://cdn.modrinth.com/data/zB8NzHon/dabe8ce18acbed2f0f33c9d2b02d139fd3f77642_96.webp"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.properties.outputs.java_version }}
      mc-version: ${{ steps.properties.outputs.minecraft_version }}
      mod-version: ${{ steps.properties.outputs.mod_version }}
      version-range: ${{ steps.properties.outputs.version_range }}
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: calculate versions
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: 'gradle.properties'
          properties: 'minecraft_version mod_version version_range java_version'

      - name: Changelog
        shell: bash
        run: |
          echo "# Changelog ${{ steps.properties.outputs.minecraft_version }} - ${{ steps.properties.outputs.mod_version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.event.release.body }}" >> $GITHUB_STEP_SUMMARY

  build-and-release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ needs.prepare.outputs.java-version }}
          cache: "gradle"
          cache-dependency-path: "gradle.properties"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: copy jar-files
        shell: bash
        run: |
          mkdir ./dist
          mv ./forge/build/libs/${{ env.MODID }}-*.jar ./dist
          mv ./fabric/build/libs/${{ env.MODID }}-*.jar ./dist
          mv ./neoforge/build/libs/${{ env.MODID }}-*.jar ./dist
          echo -e "$(ls -lahG ./dist)"

      - name: Add files to GitHub-Release
        uses: shogo82148/actions-upload-release-asset@v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./dist/${{ env.MODID }}-*.jar"
          overwrite: true

          
